modules nécessaires

groff have a basic install with any flavor of linux. However, if you want to use
it fully, you'll need to install additional packages.

dnf install groff: add necessary package to base install
dnf install groff-doc: not mandatory, but you'll have all groff doc on your system.
dnf install groff-perl: Include amoung other post-processor gropdf to create pdf files.
dnf install perl-IO-Zlib pour la librairie de compression ZLib


